# Generated by Django 5.0.6 on 2024-06-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HexaCafe', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
